name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello, thank you for creating a issue. I appreciate it. I will look onto it ASAP. Thanks."
        pr-message: "Hey, thank you for your PR and trying to improve my program."
